
[ClassVersion("1.0.0"), FriendlyName("XD7Site")]
class VE_XD7Site : OMI_BaseResource
{
    [Key, Description("Citrix XenDesktop 7 site name.")] String SiteName;
    [Required, Description("MS SQL Server hostname/instance name hosting the XenDesktop 7 database.")] String DatabaseServer;
    [Required, Description("Citrix XenDesktop 7 site database name.")] String SiteDatabaseName;
    [Required, Description("Citrix XenDesktop 7 logging database name.")] String LoggingDatabaseName;
    [Required, Description("Citrix XenDesktop 7 monitor database name.")] String MonitorDatabaseName;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies a user account that has permission to create the site.")] String Credential;
};
