
[ClassVersion("1.0"), FriendlyName("XD7StoreFrontStore")]
class VE_XD7StoreFrontStore : OMI_BaseResource
{
	[Key, Description("Citrix StoreFront name")] String StoreName;
	[Required, Description("Citrix StoreFront Authentication type"), ValueMap{"Explicit","Anonymous"}, Values{"Explicit","Anonymous"}] String AuthType;
	[Required, Description("Citrix StoreFront farm name")] String FarmName;
	[Write, Description("Citrix StoreFront port")] UInt32 Port;
	[Write, Description("Citrix StoreFront transport type"), ValueMap{"HTTP","HTTPS","SSL"}, Values{"HTTP","HTTPS","SSL"}] String TransportType;
	[Required, Description("Citrix StoreFront director servers")] String Servers[];
	[Write, Description("Citrix StoreFront enable load balancing")] Boolean LoadBalance;
	[Write, Description("Citrix StoreFront farm type"), ValueMap{"XenApp","XenDesktop","AppController"}, Values{"XenApp","XenDesktop","AppController"}] String FarmType;
	[Write, Description("Citrix StoreFront authenication service virtual path")] String AuthVirtualPath;
	[Write, Description("Citrix StoreFront store virtual path")] String StoreVirtualPath;
	[Write, Description("Citrix StoreFront site id")] UInt64 SiteId;
	[Write, Description("Citrix StoreFront service urls")] String ServiceUrls[];
	[Write, Description("Citrix StoreFront ssl relay port")] UInt32 SSLRelayPort;
	[Write, Description("Citrix StoreFront all failed bypass duration")] UInt32 AllFailedBypassDuration;
	[Write, Description("Citrix StoreFront bypass duration")] UInt32 BypassDuration;
	[Write, Description("Citrix StoreFront zones")] String Zones[];
	[Write, Description(" All the resources delivered by locked-down Store are auto subscribed and do not allow for un-subscription")] Boolean LockedDown;
	[Write, Description("Ensure"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
