
[ClassVersion("1.0.0"), FriendlyName("XD7Database")]
class VE_XD7Database : OMI_BaseResource
{
    [Key, Description("Citrix XenDesktop 7 site name.")] String SiteName;
    [Key, Description("Citrix XenDesktop 7 database name.")] String DatabaseName;
    [Required, Description("MS SQL Server hostname/instance name hosting the XenDesktop 7 database")] String DatabaseServer;
    [Required, Description("Citrix XenDesktop 7 database type to create."), ValueMap{"Site","Logging","Monitor"}, Values{"Site","Logging","Monitor"}] String DataStore;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies a user account that has permission to create the site database.")] String Credential;
};
