
[ClassVersion("1.0"), FriendlyName("XD7StoreFrontStoreBase")]
class VE_XD7StoreFrontStoreBase : OMI_BaseResource
{
	[Key, Description("Citrix StoreFront name")] String StoreName;
	[Required, Description("Citrix StoreFront Authentication type"), ValueMap{"Explicit","Anonymous"}, Values{"Explicit","Anonymous"}] String AuthType;
	[Write, Description("Citrix StoreFront authenication service virtual path")] String AuthVirtualPath;
	[Write, Description("Citrix StoreFront store virtual path")] String StoreVirtualPath;
	[Write, Description("Citrix StoreFront site id")] UInt64 SiteId;
	[Write, Description("All the resources delivered by locked-down Store are auto subscribed and do not allow for un-subscription")] Boolean LockedDown;
	[Write, Description("Allow sessions to be reconnected")] Boolean AllowSessionReconnect;
	[Write, Description("Substitute the desktop image provided by XenApp or XenDesktop with the StoreFront default")] Boolean SubstituteDesktopImage;
	[Write, Description("Ensure"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
