[ClassVersion("1.0.0.0"), FriendlyName("XD7StoreFrontFarmConfiguration")]
class VE_XD7StoreFrontFarmConfiguration : OMI_BaseResource
{
	[Key, Description("StoreFront store name")] String StoreName;
	[Write, Description("Enable file type association")] Boolean EnableFileTypeAssociation;
	[Write, Description("Communication timeout when using to the Xml service in seconds")] String CommunicationTimeout;
	[Write, Description("Connection timeout when connecting to the Xml service in seconds")] String ConnectionTimeout;
	[Write, Description("Period of time before retrying a XenDesktop 7 and greater farm in failed leasing mode in seconds")] String LeasingStatusExpiryFailed;
	[Write, Description("Period of time before retrying a XenDesktop 7 and greater farm in leasing mode in seconds")] String LeasingStatusExpiryLeasing;
	[Write, Description("Period of time before retrying a XenDesktop 7 and greater farm pending leasing mode in seconds")] String LeasingStatusExpiryPending;
	[Write, Description("Use pooled sockets")] Boolean PooledSockets;
	[Write, Description("Number of server connection attempts before failing")] UInt32 ServerCommunicationAttempts;
	[Write, Description("Period of time between polling XenApp\XenDesktop server health in seconds")] String BackgroundHealthCheckPollingPeriod;
	[Write, Description("Indicates whether an advanced health-check should be performed")] Boolean AdvancedHealthCheck;
};
