
[ClassVersion("1.0.0"), FriendlyName("XD7CatalogMachine")]
class VE_XD7CatalogMachine : OMI_BaseResource
{
    [Key, Description("Citrix XenDesktop 7 machine catalog name.")] String Name;
    [Required, Description("Citrix XenDesktop 7 machine catalog computer members.")] String Members[];
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies a user account that has permission to create the role.")] String Credential;
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
};
