
[ClassVersion("1.0.0.0"), FriendlyName("XD7StoreFrontRoamingGateway")]
class VE_XD7StoreFrontRoamingGateway : OMI_BaseResource
{
	[Key, Description("Gateway friendly name")] String Name;
	[Required, Description("The login type required and supported by the Gateway"), ValueMap{"UsedForHDXOnly","Domain","RSA","DomainAndRSA","SMS","GatewayKnows","SmartCard","None"}, Values{"UsedForHDXOnly","Domain","RSA","DomainAndRSA","SMS","GatewayKnows","SmartCard","None"}] String LogonType;
	[Write, Description("The login type to use when SmartCard fails")] String SmartCardFallbackLogonType;
	[Write, Description("The Citrix NetScaler Gateway version")] String Version;
	[Required, Description("The Gateway Url")] String GatewayUrl;
	[Write, Description("The Gateway authentication call-back Url")] String CallbackUrl;
	[Write, Description("Enable session reliability")] Boolean SessionReliability;
	[Write, Description("Request STA tickets from two STA servers")] Boolean RequestTicketTwoSTAs;
	[Write, Description("IP address")] String SubnetIPAddress;
	[Write, Description("Secure Ticket Authority server Urls")] String SecureTicketAuthorityUrls[];
	[Write, Description("Load balance between the configured STA servers")] Boolean StasUseLoadBalancing;
	[Write, Description("Time before retrying a failed STA server")] String StasBypassDuration;
	[Write, Description(" GSLB domain used by multiple gateways")] String GslbUrl;
	[Write, Description("Ensure"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
