
[ClassVersion("1.0.0"), FriendlyName("XD7VDAFeature")]
class VE_XD7VDAFeature : OMI_BaseResource
{
    [Key, Description("Citrix XenDesktop 7 VDA feature."), ValueMap{"DesktopVDA","SessionVDA"},Values{"DesktopVDA","SessionVDA"}] String Role;
    [Required, Description("Citrix XenDesktop 7 installation media source path.")] String SourcePath;
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Specifies a user account that has permission to install the feature.")] String Credential;
    [Write, Description("Install Citrix Receiver.")] Boolean InstallReceiver;
    [Write, Description("Enable the Microsoft Remote Assistance feature.")] Boolean EnableRemoteAssistance;
    [Write, Description("Optimize the VDA installation for a virtual desktop.")] Boolean Optimize;
    [Write, Description("Enable the Desktop Experience feature.")] Boolean InstallDesktopExperience;
    [Write, Description("Enable UDP Real-time transport feature.")] Boolean EnableRealTimeTransport;
    [Write, Description("Excludes the Citrix Telemetry Service from the install.")] Boolean ExcludeTelemetryService;
    [Write, Description("Installation log path")] String LogPath;
};
