
[ClassVersion("1.0.0.0"), FriendlyName("XD7StoreFrontOptimalGateway")]
class VE_XD7StoreFrontOptimalGateway : OMI_BaseResource
{
	[Key, Description("StoreFront gateway name")] String GatewayName;
	[Write, Description("Site Id")] UInt64 SiteId;
	[Required, Description("Resources Virtual Path")] String ResourcesVirtualPath;
	[Required, Description("Hostnames")] String Hostnames[];
	[Required, Description("Secure Ticket Authority server Urls")] String StaUrls[];
	[Write, Description("Load balance between the configured STA servers")] Boolean StasUseLoadBalancing;
	[Write, Description("Time before retrying a failed STA server")] String StasBypassDuration;
	[Write, Description("Enable session reliability")] Boolean EnableSessionReliability;
	[Write, Description("Request STA tickets from two STA servers")] Boolean UseTwoTickets;
	[Write, Description("Farms")] String Farms[];
	[Write, Description("Zones")] String Zones[];
	[Write, Description("Enabled On Direct Access")] Boolean EnabledOnDirectAccess;
	[Write, Description("Ensure"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
